server:
  port: 8080
  tomcat:
    max-threads: 500
    min-spare-threads: 50

spring:
  application:
    name: spring-simple-demo-admin-java
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: live

# apollo配置
#apollo:
#  bootstrap:
#    enabled: true
#    namespaces: application,application.yml

mybatis-plus:
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mappers/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.gy.framework.demo.dao.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: null
