spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      druid:
        initial-size: 5
        max-active: 20
        min-idle: 5
        max-wait: 30000
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 0
        validation-query: select 1
        validation-query-timeout: -1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat,wall
        share-prepared-statements: true
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8
          username: root
          password: 12345678
          driver-class-name: com.mysql.jdbc.Driver
        slave_1:
          url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8
          username: root
          password: 12345678
          driver-class-name: com.mysql.jdbc.Driver

csrf:
  ## 验证方式(referer/token)(多种使用";"分隔)
  types: token
  ## referer验证方式下的url(多种使用";"分隔，使用token方式可以不配置)
  #referers: http://www.xxx.com
  ## token验证方式下的token参数名(使用referer方式可以不配置)
  paramName: csrf_token
  ## token验证方式下的cookie名(使用referer方式可以不配置)
  tokenName: csrf_token_cookie
  ## token验证方式下的token生成地址(使用referer方式可以不配置)
  tokenUrl: /api/token
  ## token验证方式下的cookie有效期(单位:s)(使用referer方式可以不配置)
  tokenMaxAge: 7200